if [ ! -d $DB_CONTAINER_PATH/$DATABASE_NAME ]
then
	mariadb-install-db
	service mariadb start
	sleep 2
	mariadb -e "
	CREATE DATABASE $DATABASE_NAME;
	CREATE USER '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_USER_PASSWORD';
	GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$DATABASE_USER'@'%';
	ALTER USER 'root'@'localhost' IDENTIFIED BY '$DATABASE_ROOT_PASSWORD';
	FLUSH PRIVILEGES;
	"
	mysqladmin shutdown -p$DATABASE_ROOT_PASSWORD
fi
exec mariadbd-safe
