services :
  my_service :
    build :
      context : my_service
      args :
        SSL_CONTAINER_PATH : $SSL_CONTAINER_PATH
        DOMAIN_NAME : $DOMAIN_NAME
        WORDPRESS_CONTAINER_PATH : $WORDPRESS_CONTAINER_PATH
    ports :
      - 443:443
      - 9000:9000
      - 3306:3306
    env_file :
    - .env
    - $CREDENTIALS_HOST_PATH
    volumes :
    - $WORDPRESS_HOST_PATH:$WORDPRESS_CONTAINER_PATH
    - $DB_HOST_PATH:$DB_CONTAINER_PATH
