services :
  nginx :
    build :
      context : requirements/nginx
      args :
        SSL_CONTAINER_PATH : $SSL_CONTAINER_PATH
        DOMAIN_NAME : $DOMAIN_NAME
        WORDPRESS_CONTAINER_PATH : $WORDPRESS_CONTAINER_PATH
    ports :
      - 443:443
    volumes :
      - $WORDPRESS_HOST_PATH:$WORDPRESS_CONTAINER_PATH
    env_file :
    - .env
    - $CREDENTIALS_HOST_PATH
